@localhost = localhost:4004/odata/v4/main

@id = 30a84a1b-b405-4261-9abf-9ce0ddbd550a

GET http://{{localhost}}/Customers
Content-Type: application/json

###

POST http://{{localhost}}/Customers
Content-Type: application/json

{   "id": "{{id}}",
    "firstName": "Thalia",
    "lastName": "Guedes",
    "email": "tguedes@example.com"
}

###

DELETE http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

###

PUT http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

{
    "firstName": "teste1"
}

###

PATCH http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

{
    "firstName": "teste2"
}
