@localhost = localhost:4004/odata/v4/main
@id = 539966d4-e645-4665-b099-db9231f88bf1
@customerId = 30a84a1b-b405-4261-9abf-9ce0ddbd550a

@productId = e1e003e2-5167-46c6-9c50-6b68ce1950a5

GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

###

GET http://{{localhost}}/SalesOrderHeaders?$filter=id eq {{id}}&$expand=items
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "items": [
        {
            "id": "b9d18e43-4074-4c4b-b693-eed2d5d79ea9",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "43303caa-d432-412b-aa63-1224831077ee",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###

PATCH http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###

# Buscar todos os pedidos maiores ou iguais a 90
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 90

###

# Buscar todos os pedidos menores ou iguais a 50
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 50

###

# Expandir os itens do pedido
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product),customer

###

# Filtrar os pedidos pelo total de 50 e expandir os itens do pedido
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product;$filter=quantity le 99),customer

###

#Selecionar somente customes e id dos salesOrderHeaders
GET http://{{localhost}}/SalesOrderHeaders?$select=customer,id

###

# Selecionar somente email do customer
GET http://{{localhost}}/SalesOrderHeaders?$select=customer,id&$expand=customer($select=email)
