@localhost = localhost:4004/odata/v4/main
@id = 539966d4-e645-4665-b099-db9231f88bf1
@customerId = 30a84a1b-b405-4261-9abf-9ce0ddbd550a

@productId1 = 26220727-09af-4bca-8435-376b52289ee7

@productId2 = 95490858-d6b1-4090-8818-1d12c3a2765c


GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

###

GET http://{{localhost}}/SalesOrderHeaders?$filter=id eq {{id}}&$expand=items
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    "customer_id": "25227279-2642-400b-8a3d-9ffac226450f",
    "items": [
        {
            "id": "b9d18e43-4074-4c4b-b693-eed2d5d79ea9",
            "header_id": "{{id}}",
            "product_id": "{{productId1}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "43303caa-d432-412b-aa63-1224831077ee",
            "header_id": "{{id}}",
            "product_id": "{{productId2}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###

PATCH http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###

# Buscar todos os pedidos maiores ou iguais a 90
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 90

###

# Buscar todos os pedidos menores ou iguais a 50
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 50

###

# Expandir os itens do pedido
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product),customer

###

# Filtrar os pedidos pelo total de 50 e expandir os itens do pedido
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product;$filter=quantity le 99),customer

###

#Selecionar somente customes e id dos salesOrderHeaders
GET http://{{localhost}}/SalesOrderHeaders?$select=customer,id

###

# Selecionar somente email do customer
GET http://{{localhost}}/SalesOrderHeaders?$select=customer,id&$expand=customer($select=email)

###

# Descobrindo a quantidade de registros
GET http://{{localhost}}/SalesOrderHeaders/$count

###

# Paginando os registros
GET http://{{localhost}}/SalesOrderHeaders?$top=3&$skip=0

###

# Buscando dados com search
GET http://{{localhost}}/SalesOrderHeaders?$search=2kcg

###
